name: Publish Node to Comfy Registry

on:
  push:
    branches:
      - main  # 触发工作流的分支，确保是你的默认分支
    paths:
      - "pyproject.toml"  # 仅当 pyproject.toml 文件发生变化时触发工作流

jobs:
  publish-node:
    runs-on: ubuntu-latest  # 在 Ubuntu 上运行
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 获取 GitHub 仓库的代码

      - name: Set up Python
        uses: actions/setup-python@v2  # 设置 Python 环境
        with:
          python-version: 3.9  # 设置 Python 版本，确保与你的项目兼容

      - name: Install comfy-cli
        run: pip install comfy-cli  # 安装 comfy-cli

      - name: Publish Node
        run: comfy node publish  # 运行发布命令
        env:
          API_KEY: ${{ secrets.REGISTRY_ACCESS_TOKEN }}  # 从 GitHub Secrets 中读取并传递 API Key